session_name: demo
environment:
  CYCLONEDDS_URI: file://${HOME}/ws/install/shm_vision_demo/share/shm_vision_demo/config/cyclonedds.xml
  ROUDI_CONFIG: ${HOME}/ws/install/shm_vision_demo/share/shm_vision_demo/config/roudi_config.toml
  VIDEO_PATH: ${HOME}/video.mp4
shell_command_before:
  - cd ws; source ./install/setup.bash
windows:
  - window_name: ROS nodes (Foreground)
    layout: "tiled"
    panes:
      - ros2 run shm_vision_demo object_detector
      - ros2 run shm_vision_demo display
  - window_name: ROS nodes (Background)
    layout: "tiled"
    panes:
      - iox-roudi -c ${ROUDI_CONFIG}
      - ros2 run shm_vision_demo camera ${VIDEO_PATH}
      - ros2 run shm_vision_demo filter
      - ros2 run shm_vision_demo edge_detector
      - ros2 run shm_vision_demo optical_flow
  - window_name: Performance
    panes:
      - sudo btm
