session_name: demo
environment:
  VIDEO_PATH: ${HOME}/video.mp4
shell_command_before:
  - cd ws; source ./install/setup.bash
windows:
  - window_name: ROS nodes (Foreground)
    layout: "tiled"
    panes:
      - ros2 run shm_vision_demo object_detector
      - ros2 run shm_vision_demo display
      - btm --config ../configs/btm.toml
  - window_name: ROS nodes (Background)
    layout: "tiled"
    panes:
      - ros2 run shm_vision_demo camera ${VIDEO_PATH}
      - ros2 run shm_vision_demo filter
      - ros2 run shm_vision_demo edge_detector
      - ros2 run shm_vision_demo optical_flow

